{"uuid": "1323fbc1-270e-42ec-a8d4-0acc7ad480d5", "children": ["5a0af072-b216-4fb6-bf3c-8373de04ae72"], "befores": [{"name": "xunit_setup_method_fixture_TestEnterPrise", "status": "passed", "start": 1657453030290, "stop": 1657453030290}], "afters": [{"name": "xunit_setup_method_fixture_TestEnterPrise::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestEnterPrise' object has no attribute 'balance'\n", "trace": "  File \"D:\\MyApp\\Python-3.8.8\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\MyApp\\Python-3.8.8\\lib\\site-packages\\_pytest\\fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\MyApp\\Python-3.8.8\\lib\\site-packages\\_pytest\\python.py\", line 845, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"D:\\MyApp\\Python-3.8.8\\lib\\site-packages\\_pytest\\python.py\", line 741, in _call_with_optional_argument\n    func()\n  File \"E:\\文档\\MyRepository\\ui-automation-framework\\cases\\case_enterprise\\test_001_login.py\", line 80, in teardown_method\n    conf.set(\"Balance\", \"balance\", self.balance)\n"}, "steps": [{"name": "缓存账号余额", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestEnterPrise' object has no attribute 'balance'\n", "trace": "  File \"E:\\文档\\MyRepository\\ui-automation-framework\\cases\\case_enterprise\\test_001_login.py\", line 80, in teardown_method\n    conf.set(\"Balance\", \"balance\", self.balance)\n"}, "start": 1657453077678, "stop": 1657453077678}], "start": 1657453077678, "stop": 1657453077680}], "start": 1657453030290, "stop": 1657453077680}